version: '3.3'
services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - '80:80'
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        environment:
            - PORT=5000
